# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: meetPouya
name: Pouya
description: >- # this means to ignore newlines until "baseurl:"
keywords: ['meetPoyua', 'Pouya', 'Projects', 'Ideas', 'Blog']
baseurl: '' # the subpath of your site, e.g. /`blog
url: 'https://meetpouya.github.io/' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'meetpouya.github.io' # the domain name for your site, e.g. example.com
language: en

analytics: # the Google Analytics property ID, e.g. UA-XXXXX-Y

comments: false # enable comments
disqus: # disqus account

mathjax: true # Math support
diagram: true # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
