# Welcome to Jekyll-Paper!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pouya
email: mpouyamirzaei@gmail.com
name: Pouya M.
description: >- # this means to ignore newlines until "baseurl:"
  Pouya's tinkering blog.
keywords: [Healthcare, Engineering, Science, Biomedical, Data Science, Machine Learning, Artificial Intelligence, Python, R, Matlab, C++, C, Java, SQL, HTML, CSS, JavaScript, Ruby, Ruby on Rails, Jekyll, Git, GitHub, Linux, Windows, MacOS, Android, iOS, Web Development, Software Development, Data Analysis, Data Visualization, Data Management, Data Mining, Data Cleaning, Data Wrangling, Data Preprocessing, Data Transformation, Data Integration, Data Engineering, Data Modeling, Data Architecture, Data Governance, Data Quality, Data Security, Data Privacy, Data Ethics, Data Strategy, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency, Data Culture, Data Science, Data Scientist, Data Analyst, Data Engineer, Data Architect, Data Manager, Data Governance, Data Stewardship, Data Literacy, Data Fluency,]
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://meetpouya.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "meetpouya.github.io" # the domain name for your site, e.g. example.com
language: en

analytics:   # the Google Analytics property ID, e.g. UA-XXXXX-Y

paginate: 25
paginate_path: "/page:num/"

comments: false  # enable comments
disqus:          # disqus account

mathjax: true # Mathematics
mermaid: true # Diagrams

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Category settings
jekyll-archives:
  enabled: 
    - categories
    - tags
  layout: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
